### ISSUE TITLE
ordre des layers

### ISSUE THREAD

**Issue by Lazare** [ludo456/Gribouillot#1]
Je viens de réaliser que lorsque le nombre de layer dépasse 9 il y a un problème d'ordre lors de la sauvegarde/restauration du fichier .grib

en effet les layers sont ordonné par ordre alphabetique des clefs [layerX] et donc on obtient lors de la sauvegarde
[layersOrder]
layer10=titre_10
layer1=titre_1
layer2=titre_2
layer3=titre_3
layer4=titre_4
layer5=titre_5
layer6=titre_6
layer7=titre_7
layer8=titre_8
layer9=titre_9

il est possible de corriger cela en editant le ficher, mais le problème réparait à la prochaine sauvegarde.

**Comment by Lazare** [comment]
Je en sais pas si les tickets de bugs sont les bienvenus, dans le cas contraire n’hésitez pas à le dire.
Mais sans doute que ce problème avait déjà été corrigé et que ma version date un peu.

**Comment by ludo456** [comment]
Les tickets sont bienvenus. Pour éviter les doublons j'ai mis à jour la liste des ISSUES de la v2. Mes commits compilent donc pour ceux qui veulent la version "dev" il suffit d'installer la SDK et recompiler avec le dernier code source.
