### ISSUE TITLE
middle mouse pan

### ISSUE THREAD

**Issue by dddjef** [ludo456/Gribouillot#44]
Super travail! Je suis entrain de le tester, et il y a plein de bonnes idées.
Tu penses qu'il serait possible d'avoir une option pour que le bouton du milieu de la souris servent à se déplacer latéralement dans la vue quand il est maintenu? et que la molette servent à zoomer (sans maintenir CTRL) ?

**Comment by ludo456** [comment]
_Déplacement latéral :_ utiliser la molette justement en plaçant le curseur au-dessus de la barre de scroll inférieure.
_Zoom avec la molette sans Ctrl :_ Non justement cela remplacerait un comportement "attendu" de la molette. Elle permet actuellement de se déplacer en scroll haut/bas comme dans la majorité des applications (par exemple le navigateur Internet)

**Comment by dddjef** [comment]
Comme tu veux, je dois trop être habitué aux logiciels graphiques :)
