### ISSUE TITLE
echelle de la carte exprimee en km pas assez précise

### ISSUE THREAD

**Issue by dddjef** [ludo456/Gribouillot#45]
la 989 maxi a normalement une echelle de 1 px  = 169m
si je me mets en mètre, pour indiquer cette echelle, je suis bloqué dans d'autres outils. Par exemple c'est impossible de faire un cercle de 66km, car pour indiquer le rayon, je ne peux dépasser 9999 et que les unités sont bloquées en mètre.
Si d'un autre côté j'indique l'échelle de la carte en km, je suis bloquéà deux décimales, donc je ne peux préciser 0,169 km , mais seulement 0,16 ou 0,17. D'où un manque de précision pour la suite.

**Comment by ludo456** [comment]
_Work around:_ 1px = 169m = 0,169km => 10px = 1,69km.

**Comment by dddjef** [comment]
ça marche, merci

**Comment by Fr3nchK1ss** [comment]
Work-around is the solution.
