### ISSUE TITLE
add shortcuts for zoom

### ISSUE THREAD

**Issue by Lazare** [ludo456/Gribouillot#48]
Je suis, contre mon gré, contraint d'utiliser un mac. J'ai donc installé Gribouillot sur linux dans machine virtuelle (virtualbox).

Pour le moment je n'ai pas trouvé de moyen efficace d'émuler la roulette de la souris et je n'ai donc pas accès aux fonctions de zoom. La solution qui me paraitrait la plus simple pour les gens dans le même cas que moi serait d'ajouter des raccourcis (CTRL + "+" et CTRL + "-" me sembleraient particulièrement adaptés)

**Comment by Fr3nchK1ss** [comment]
More of a 5$ hardware problem in a complex setup (virtualbox).
